services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoNewsSorting\:
        resource: ../src

    InspiredMinds\ContaoNewsSorting\EventListener\NewsFilterEventListener:
        arguments: ['@contao_news_filter_event.news_list_hook_listener']
