services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoNewsSorting\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoNewsSortingBundle.php}

    InspiredMinds\ContaoNewsSorting\EventListener\NewsListHookListener:
        decorates: contao_news_filter_event.news_list_hook_listener
